env: "cartpole_continuous"
env_cfg:
  _target_: mbrl.env.cartpole_continuous.CartPoleEnv
  x_constraints: False
  theta_constraints: False
  x_starting: 2.5
term_fn: no_termination
 
learned_rewards: false
trial_length: 200
num_steps: 5000

num_elites: 5
model_lr: 7.5e-4
model_wd: 3e-5
model_batch_size: 256
validation_ratio: 0
freq_train_model: 50
patience: 25
num_epochs_train_model: 25

planning_horizon: 15
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 350
cem_alpha: 0.1
cem_clipped_normal: false

evaluate_dataset_path: "/checkpoint/pakamienny/model-based/pets/operon_ensemble/cartpole_continuous/2022.05.18/062804"
