name: "pets"
dataset_size: 10000

agent:
  _target_: mbrl.planning.TrajectoryOptimizerAgent
  action_lb: ???
  action_ub: ???
  planning_horizon: ${overrides.planning_horizon}
  optimizer_cfg: ${action_optimizer}
  replan_freq: 1
  verbose: ${debug_mode}

model_trainer: ${dynamics_model.model_trainer}
reinitialize_models: ${dynamics_model.reinitialize_models} 
normalize: ${dynamics_model.normalize}
normalize_double_precision: ${dynamics_model.normalize_double_precision}
target_is_delta: ${dynamics_model.target_is_delta}

initial_exploration_steps: ${overrides.trial_length}
freq_train_model: ${overrides.freq_train_model}
learned_rewards: ${overrides.learned_rewards}


num_particles: 20
