_target_: mbrl.models.SymbolicRegressor
device: ${device}
in_size: ???
out_size: ???
ensemble_size: 2
deterministic: true
propagation_method: random_model


scale_x: false
scale_y: true
base_regressor_cfg:
  _target_: sklearn.neural_network.MLPRegressor
  hidden_layer_sizes: [500,500,500]
  shuffle: True
  learning_rate_init: 3e-4
  max_iter: 250
  activation: "relu"
  learning_rate: "adaptive"
  warm_start: true
  verbose: true

name : custom_mlp_ensemble

model_trainer: 
  _target_: mbrl.models.SymbolicModelTrainer

reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false