_target_: mbrl.models.GaussianMLP
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
ensemble_size: 7
hid_size: 200
deterministic: false
propagation_method: random_model
learn_logvar_bounds: false  # so far this works better
activation_fn_cfg:
  _target_: torch.nn.SiLU

name : gaussian_mlp_ensemble


model_trainer: 
  _target_: mbrl.models.ModelTrainer
  optim_lr: ${overrides.model_lr}
  weight_decay: ${overrides.model_wd}

reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false