_target_: mbrl.models.SymbolicRegressor
device: ${device}
in_size: ???
out_size: ???
ensemble_size: 5
deterministic: true
propagation_method: random_model


scale_x: false
scale_y: true

base_regressor_cfg:
  _target_: sklearn.gaussian_process.GaussianProcessRegressor

name : gp_ensemble

model_trainer: 
  _target_: mbrl.models.SymbolicModelTrainer

reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false