# @package _group_
_target_: mbrl.models.GaussianMLP
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
ensemble_size: 1
hid_size: 200
deterministic: true
activation_fn_cfg:
  _target_: torch.nn.SiLU
name : mlp

model_trainer: ModelTrainer
reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false
