_target_: mbrl.models.SymbolicRegressor
device: ${device}
in_size: ???
out_size: ???
ensemble_size: 3
deterministic: true
propagation_method: random_model

scale_x: false
scale_y: false

base_regressor_cfg:
  _target_: operon.sklearn.SymbolicRegressor
  local_iterations: 5
  generations: 10000
  n_threads: 10
  population_size: 5000
  allowed_symbols: 'add,sub,mul,div,constant,variable,sin,cos,pow'   

name : operon_ensemble

model_trainer: 
  _target_: mbrl.models.SymbolicModelTrainer

reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false