_target_: mbrl.models.Operon
device: ${device}
in_size: ???
out_size: ???
ensemble_size: 2
deterministic: true
propagation_method: random_model

name : operon_ensemble

model_trainer: 
  _target_: mbrl.models.SymbolicModelTrainer

reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false