_target_: mbrl.models.Operon
device: ${device}
in_size: ???
out_size: ???
ensemble_size: 7
hid_size: 200
deterministic: true
propagation_method: random_model

name : gaussian_mlp_ensemble

model_trainer: ModelTrainer
reinitialize_models: true 
normalize: false
normalize_double_precision: true
target_is_delta: false